:global:
  componentName: cilium
  githubUrl: https://github.com/projectsyn/component-cilium
  feature_goldenTests: true

docs/antora.yml:
  name: cilium
  title: Cilium
.github/workflows/test.yaml:
  test_makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
  matrix:
    key: instance
    entries:
      - defaults
