:global:
  componentName: cilium
  githubUrl: https://github.com/projectsyn/component-cilium
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - defaults
      - helm-opensource
      - olm-opensource

docs/antora.yml:
  name: cilium
  title: Cilium

.github/workflows/test.yaml:
  test_makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
.gitignore:
  additionalEntries:
    - dependencies/cilium/olm/
    - jsonnetfile.json
