= Cilium

cilium is a Commodore component to manage the Cilium networkplugin.

See the xref:references/parameters.adoc[parameters] reference for further details on how to use the component to configure and deploy Cilium.

== Metrics scraping

By default, the component enables the metrics endpoint for the Cilium agent.
The component assumes that prometheus-operator will be present on the target cluster, and creates a `ServiceMonitor` resource for the agent metrics endpoint.

See the https://docs.cilium.io/en/v1.11/operations/metrics/#cilium-agent[Cilium docs] for available agent metrics.

== Aggregated permissions

The component creates the following `ClusterRoles` which are aggregated to the cluster's default `ClusterRoles`:

[cols="1,1,1"]
|===
|Name |Resources |Aggregated to

|`syn-cilium-view`
a|
* `ciliumnetworkpolicies.cilium.io`
* `ciliumendpoints.cilium.io`
a|
* `view`
* `edit`
* `admin`

|`syn-cilium-edit`
a|
* `ciliumnetworkpolicies.cilium.io`
a|
* `edit`
* `admin`

|`syn-cilium-cluster-reader`
|All resources in `cilium.io`
|`cluster-reader`

|===

This enables users to viewfootnote:view[View permission grants RBAC verbs `get`, `list` and `watch`] `ciliumnetworkpolicy` and `ciliumendpoint` resources in their namespaces.
Users which have `edit` or `admin` permissions in a namespace, can additionally create, modify, and delete `ciliumnetworkpolicy` resources in that namespace.
Finally, users which have `cluster-reader` permissions can viewfootnote:view[] at all resources in `cilium.io` in all namespaces.
