= CiliumClustermeshRemoteClusterNotReady

include::partial$runbooks/contribution_note.adoc[]

== icon:glasses[] Overview

This alert fires if a remote cluster is not reachable from a node for 10 minutes or longer.
This usually indicates one of the following two:

. A local issue on the node prevents the Cilium agent to connect to the remote cluster or the cluster mesh API server
. The remote cluster's cluster mesh API server is not available
. There are network issues preventing cluster mesh connectivity

TIP: Depending on the network configuration, there may be static routes on each node for the remote cluster's cluster mesh API server.

NOTE: When using KVStoreMesh, the agents on the cluster connect to the *local* cache of the remote cluster mesh API server.

== icon:bug[] Steps for debugging

NOTE: The steps in this section assume that your current Kubernetes context points to the source cluster.

TIP: This section assumes that you're running cluster mesh with the cluster mesh API server enabled.

=== Prerequisites

* `cilium` CLI, install from https://github.com/cilium/cilium-cli[icon:github[] cilium/cilium-cli]

=== Identifying the root cause

First, check the source cluster's overall cluster mesh status

[source,bash]
----
cilium -n cilium clustermesh status --as=cluster-admin <1>
----
<1> `--as=cluster-admin` is required on VSHN Managed OpenShift, may need to be left out on other clusters.

If the output indicates that all nodes are unable to connect to the remote cluster's clustermesh API, it's likely that the issue is either on the remote cluster, or in the network between the clusters.

If the output indicates that only a few source nodes are affected, it's likely that the issue is in the Cilium agent or the routing configuration of the nodes.

include::partial$runbooks/investigating-clustermesh-api.adoc[]

=== Checking connectivity from a Cilium agent pod

If the `cilium clustermesh status` output indicates that only a few nodes are affected, you can run a more detailed check from the nodes' agent pods.
In the output of these command, you should see whether the agent can connect to the cluster mesh API and whether the clustermesh certificates are still valid.

[source,bash]
----
NODE=<node name of affected node> <1>
AGENT_POD=$(kubectl -n cilium get pods --field-selector=spec.nodeName=$NODE \
  -l app.kubernetes.io/name=cilium-agent -oname)

kubectl -n cilium exec -it $AGENT_POD --as=cluster-admin -- cilium status <2>
kubectl -n cilium exec -it $AGENT_POD --as=cluster-admin -- cilium troubleshoot clustermesh <3>
----
<1> Set this to the name of an affected node's `Node` object
<2> Show a summary of the Cilium agent status.
You should see in the output of this command whether the agent can't reach one or more of the remote cluster's nodes.
<3> This command will show connection details to the remote cluster's cluster mesh API server or the local cache in case you're using KVStoreMesh.

TIP: `--as=cluster-admin` may need to be left out on some clusters.

If the output of `cilium troubleshoot clustermesh` refers to the local cluster's cluster mesh API server, it's likely that you're using KVStoreMesh.
In that case you can check the KVStoreMesh connection to the remote cluster mesh API server in the `clustermesh-apiserver` deployment:

[source,bash]
----
kubectl -n cilium --as=cluster-admin exec -it deploy/clustermesh-apiserver -c kvstoremesh -- \
   clustermesh-apiserver kvstoremesh-dbg status <1>

kubectl exec -it -n cilium --as=cluster-admin deploy/clustermesh-apiserver -c kvstoremesh -- \
  clustermesh-apiserver kvstoremesh-dbg troubleshoot <2>
----
<1> Show a connection summary of the KVStoreMesh
<2> Show connection details of the KVStoreMesh

You can also run `cilium-health status --probe` in the agent pod to actively probe the node to node connectivity:

[source,bash]
----
kubectl -n cilium exec -it $AGENT_POD --as=cluster-admin -- cilium-health status --probe
----

include::partial$runbooks/check-node-routing-tables.adoc[]

include::partial$runbooks/clustermesh-upstream-docs.adoc[]
