:helm-minor-version: v1.10

= Parameters

The parent key for all of the following parameters is `cilium`.

[NOTE]
The namespace is `cilium` and currently non configurable.

== `install_method`

[horizontal]
type:: string
default:: `helm`
possible values:: `helm`, `olm`

The installation method for Cilium.
`olm` uses the https://docs.openshift.com/container-platform/4.9/operators/understanding/olm/olm-understanding-olm.html[Openshift Operator Lifecycle Manager].
OLM installation is required for OpenShift clusters.
The Cilium OLM is a thin wrapper around Helm, because of this the Helm values are used for OLM configuration too.

.Supported Combinations
|===
| |Helm |OLM
|Opensource
|✅
|✅
|Enterprise
|✅
|✅
|===

== `release`

[horizontal]
type:: string
default:: `opensource`
possible values:: `opensource`, `enterprise`

Two version of Cilium exist.
The open-source version and the enterprise version.


== `charts.cilium.source`

[horizontal]
type:: string
default:: `https://helm.cilium.io`

The Helm repository from which to download the `cilium` Helm chart.


== `charts.cilium.version`

[horizontal]
type:: string
default:: https://github.com/projectsyn/component-cilium/blob/master/class/defaults.yml[See `class/defaults.yml`]

The version to use for the `cilium` Helm chart.

== `charts.cilium-enterprise.source`

[horizontal]
type:: string
default:: `<CILIUM-ENTERPRISE-CHART-REPO-URL>`

The chart repository URL of the `cilium-enterprise` Helm chart.
Users must provide the chart repository URL themselves in their Project Syn global or tenant configuration.

TIP: The component default is an invalid string (`<CILIUM-ENTERPRISE-CHART-REPO-URL>`) instead of `~` to make the Kapitan error message somewhat useful when the user hasn't reconfigured the chart repository.

=== Example

[source,yaml]
----
parameters:
  cilium:
    charts:
      cilium-enterprise:
        source: https://cilium-ee-charts.example.org
----

== `charts.cilium-enterprise.version`

[horizontal]
type:: string
default:: https://github.com/projectsyn/component-cilium/blob/master/class/defaults.yml[See `class/defaults.yml`]

The version to use for the `cilium-enterprise` Helm chart.

== `olm.source`

[horizontal]
type:: object
default::
+
[source,yaml]
----
opensource: https://github.com/cilium/cilium-olm/archive/master.tar.gz
enterprise: <CILIUM-ENTERPRISE-OLM-MANIFESTS-TARGZ-URL>
----

The source for the OLM manifests.
The component selects the `opensource` or `enterprise` field based on the value of component parameter `release`.
The component doesn't provide the URL of the Cilium Enterprise OLM manifests `.tar.gz` archive.
Users must provide the URL themselves in their Project Syn configuration hierarchy.

TIP: The component default is an invalid string (`<CILIUM-ENTERPRISE-OLM-MANIFESTS-TARGZ-URL>`) instead of `~` to make the Kapitan error message somewhat useful when the user hasn't reconfigured the chart repository.

=== Example

[source,yaml]
----
parameters:
  cilium:
    olm:
      source:
        enterprise: https://cilium-ee.example.com/downloads/v${cilium:olm:version}/cilium-ee-${cilium:olm:full_version}.tar.gz <1>
----
<1> The example configuration uses Reclass references to construct URL parts containing the desired version.
The component explicitly provides separate parameters for the OLM minor version and patchlevel.

== `olm.version`

[horizontal]
type:: string
example:: `1.10`
default:: https://github.com/projectsyn/component-cilium/blob/master/class/defaults.yml[See `class/defaults.yml`]

The minor version of the OLM release to download.

== `olm.patchlevel`

[horizontal]
type:: string
example:: `4`
default:: https://github.com/projectsyn/component-cilium/blob/master/class/defaults.yml[See `class/defaults.yml`]

The patch level of the OLM release to download.

== `olm.full_version`

[horizontal]
type:: string
default:: `${cilium:olm:version}.${cilium:olm:patchlevel}`

The complete version of the OLM release to download.
By default, the component constructs the value for this parameter from parameters `version` and `patchlevel`.

== `cilium_helm_values`

[horizontal]
type:: object

The configuration values of the underlying Cilium helm chart.
See https://docs.cilium.io/en/{helm-minor-version}/helm-reference/[Reference].


== `helm_values`

[horizontal]
type:: object

The final merged Helm values provided to Helm when rendering the chart.
This parameter is configured dynamically to match the expected structure for Helm chart parameters for the opensource and enterprise charts.

When the enterprise chart is used, the actual Cilium configuration is nested under key `cilium` in the Helm values and additional top-level keys exist to configure the Cilium Enterprise components.
Users should prefer to configure Cilium itself through parameter `cilium_helm_values`.


== Example

[source,yaml]
----
release_name: cilium

install_method: helm
release: opensource

cilium_helm_values:
  prometheus:
    serviceMonitor:
      enabled: false
----
